# Custom Language File for Launcher Customizer

[ejs.app]
title = "Reina Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/rafucuk/ReinaLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/jojos"

[ejs.settings]
sourceGithubLink = "https://github.com/rafucuk/ReinaLauncher"
supportLink = "https://github.com/rafucuk/ReinaLauncher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO Reina!"
welcomeDescription = "To prevent the \"two-week phase\" in Minecraft, where players quickly lose interest, modpacks and custom launchers can breathe new life into the game, creating a more engaging and long-lasting experience. By incorporating tailored modpacks, you can introduce new biomes, advanced mechanics, and unique gameplay elements that keep the experience fresh. A custom launcher simplifies the process of managing mods and provides an easy way to switch between different versions or modpacks. Additionally, an integrated authentication system ensures a secure and personalized gaming environment, fostering community interaction while keeping the experience fun and dynamic over the long term."
welcomeDescCTA = "You are just a few clicks away from Fun."
